# Rule Configuration
rules:
  indentation:
    - 2
    -
      size: 4
  class-name-format:
    - 1
    - convention: strictbem
  no-vendor-prefixes:
    - 0

files:
  ignore:
    - './resources/sass/vendors/**/*.scss'
