#!/usr/bin/env bash

# it is wrapper around docker-compose with some pre-defined handy shortcuts
# it allows you to interact with application and it's moving parts and provides means
# for getting you env ready and configured, and allows to interact with env after that

# always fail early
set -e

# Disable pseudo-TTY allocation for CI
TTY=""

# docker-compose shorthand
COMPOSE="docker-compose"

# execute command in running container
# globals:
#   $COMPOSE, $TTY
# arguments:
#   $1   - in which container to execute command
#   $2.. - command itself
function stack_exec () {
    local CONTAINER=$1; shift
    (set -x; $COMPOSE exec $TTY --user www-data $CONTAINER $@)
}

# spin up ephemeral container and run command in it
# container is removed after command is executed
# entrypoint of container is replaced with bash
# globals:
#   $COMPOSE, $TTY
# arguments:
#   $1   - in which container to execute command
#   $2.. - command itself
function stack_run () {
    local CONTAINER=$1; shift
    (set -x; $COMPOSE run $TTY --rm --user www-data --entrypoint="/bin/bash -c" $CONTAINER "$*")
}


if [ "$#" -le 0 ]; then
    usage
fi

# capture 1st arg which denotes command
COMMAND=$1; shift 1

# main switch where we detect which top-level command or modifier is passed
case $COMMAND in
    install)
        # command
        # it will just copy templates to your working dir allowing you to tinker with them
        set -x
        cp -n ./.docker/overrides/docker-compose.${1:-dev}.yml ./docker-compose.override.yml
        cp -n ./.env.example ./.env
        exit
        ;;

    *)
        # fallback
        echo ">>Running in DEV<<"
        ;;
esac

# shorthand processing switch
case $COMMAND in
    setup)
        stack_run app composer install --prefer-dist
        stack_run app yarn install
        stack_run app yarn development
        ;;

    test)
        stack_run app-test "./vendor/bin/phpunit $@"
        ;;

    yarn)
        stack_run app yarn $@ ;;

    composer)
        stack_run app composer $@ ;;

    artisan)
        stack_run app php artisan $@ ;;

    npm)
        stack_run app npm $@ ;;

    logs)
        $COMPOSE logs -f $@ ;;

    shell)
        stack_exec app bash ;;

    watch)
        stack_exec app yarn watch ;;

    *)
        $COMPOSE $COMMAND $@ ;;
esac
