version: "3.4"

x-container: &container
  image: nextsolx/ratsinformationssystem:local
  volumes:
    - .:/var/www/html:cached
  env_file:
    - .env

x-environment: &environment
  # php configuration
  PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
  PHP_XDEBUG_REMOTE_ENABLE: 1
  PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
  PHP_XDEBUG_REMOTE_PORT: 9000

services:
  app:
    <<: *container
    environment:
      <<: *environment
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      target: develop
      args:
        - USER_UID=${USER_UID:-1000}
        - USER_GID=${USER_GID:-1000}
    ports:
      - 80:80

  app-test:
    <<: *container
    environment:
      <<: *environment
      APP_ENV: testing
      APP_KEY: dca929db9304b6e9543380c3586290e8
