steps:
  - label: 'test'
    agents:
      project: ratsinfosys
    command:
      - ./devops ci build --build-arg USER_UID=$(id -u) --build-arg USER_GID=$(id -g)
      - ./devops ci setup && ./devops ci tests
