steps:
  - label: 'test'
    agents:
      project: ratsinfosys
    command:
      - ./devops ci build --build-arg USER_UID=999 --build-arg USER_GID=999
      - ./devops ci setup && ./devops ci tests
